search_folder = "/home/jan/local/home/jan/development/cad/KiCad-Spice-Library-master/Models/Optocoupler"
destination_folder = "/home/jan/local/home/jan/development/cad/KiCad-Spice-Library-master/my_lib"
check_recursive = false
check_model = true
check_subckt = true
history = [
    "DL3038A",
    "BB",
    "DL3038A",
    "OPAMP",
    "OPAMP1",
    "VC1",
    "D1N752",
    "SUB614",
    "FZT",
    "SUB614",
    "FZT",
]
history_length = "11"
decode_priority = [
    "utf-8",
    "shift_jis",
    "ISO-8859-15",
    "Windows-1252",
]
