search_folder = "/home/"
destination_folder = "/home/"
check_recursive = false
check_model = true
check_subckt = true
history = [
    "DL3038A",
    "BB",
    "DL3038A",
    "OPAMP",
    "OPAMP1",
    "VC1",
    "D1N752",
    "SUB614",
    "FZT",
    "SUB614",
    "FZT",
]
history_length = "11"
decode_priority = [
    "utf-8",
    "shift_jis",
    "ISO-8859-15",
    "Windows-1252",
]

[search_subckt]
model = ".SUBCKT"
model_pos = 0
name_pos = 1
model_end = ".ENDS"
continuation = true
max_comment_count = 20

[search_modrl]
model = ".MODEL"
model_pos = 2
name_pos = 1
model_end = ""
continuation = false
max_comment_count = 2
